title: "在Github上维护博客"
description: 
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions

layout: post
category: 笔记
tags: [git, github page, jekyll, jekyll-bootstrap]